### ISSUE TITLE
Running Error

### ISSUE THREAD

**Issue by DavidMoussaG** [opensha/opensha-apps#12]
I cloned all the files onto my computer.
I changed directory into opensha-dev.
Whenever I try ./gradlew assemble

It gives me this error

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\dmoussa\Desktop\David\Seismology\New folder\opensha-apps\build.gradle' line: 35

* What went wrong:
A problem occurred evaluating project ':opensha-apps'.
> Could not resolve all files for configuration ':opensha-apps:compileAndResource'.

It is the same error message in all directories.

Can you please help me with this issue?

**Comment by kevinmilner** [comment]
Hello,

Does this problem persist? I can't reproduce it, and some searching indicates that it might be due to internet connection/firewall issues, e.g., https://stackoverflow.com/questions/25243342/gradle-build-is-failing-could-not-resolve-all-dependencies-for-configuration

Are you trying to edit/compile our code directly, or just use an application? If the latter, I suggest that you download a release from here: https://github.com/opensha/opensha-apps/releases/

**Comment by kevinmilner** [comment]
Closing this as we received no response, and it was likely a firewall or internet connection issue.
